## Refrences
1.  Hector Cuesta (2013) Practical Data Analysis. Birmingham, UK: Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=e250xww&AN=654543&site=eds-live&scope=site (Accessed: 18 October 2023).
2. Topre, G. (2022). Bank Customer Churn Dataset. [online] www.kaggle.com. Available at: https://www.kaggle.com/datasets/gauravtopre/bank-customer-churn-dataset.

# 1. Introduction

### 1.1 What is data
Data is plain facts gathered within a defined context. Statistians would refer to it as a set of obsevations, which contained within variables or columns whith columns possessing varying/unique characteristics. Data can also be referred to as a piece of information after it has been summarised, and when subjected to analysis, data can be referred to as evidence of a hypothesis. Before data can become information and utilmately evidence it must go through a process. Data analysis is the process in which raw data is ordered and organized, to be used in methods that help to explain the past and predict the future (Hector, 2013).
Data anslysis requires good use os statiscal thechniques and probability in other to understand, summarise and efficiently and accurately manipulate data hence facilitating making reliable predicts to statakeholders of a domain. In this project we would be using satistical and probability thechniques to summarise Bank churn dataset and ultimately draw conclusion as informed by our analysis. 
### 1.2 Forms of data
Data is a generalised term, but within this term are branches which can be referred to as forms/ types. Data can broadly be divided into 2 types:
1. Categorical types: Categorical datas are also reffred to as qualititative datas. This are datas that can not be measured. They are in general any form of data that is not in numerical for. E.g smoker/ non-smoker. 
2. Numerical types: Numerical data on the otherhand are datas that are in number form E.g. [Age: 20,18..]. They are also called quantitative datas, this meas they can be quantified by numbers, and increament is also propotinal to quantity for example an 18year old person is more aged than a 2year old person. 
It is worth saying that this 2 data tyoes are just a broad overveiw of forms in which a data can be presented, however each data type has sub-division in them and they mean diffrent things as relating to characteristics of such data and how they would be treated in analysis. 
### 2. Understanding 'Bank churn' dataset
The Bank churn dataset i have chosen to analyse is from ABC Multistate bank (Topre, 2022). Customer churn in simple term is when a customer of an organisation decides to path ways with the bussiness. In this contest ABC multistate bank customer churn would be when a customer of the bank discontinue their patronage of the bank services. This data set has 12 variables in it, and the bank wasnts to be able to see how each if this columns influence a coustomers decision to churn the bank. The data is available in 
### 2.1 Data source
This data is available in comma separated format, and has been downloaded from Kaggle open source. 
### 2.2 Columns defination (Topre, 2022).
customer_id: Uniques identification of coustomer. 
credit_score: Credit score of each coustomer
country: This is the region the coustomer is based.
Gender: This is the gender of each uniqe customer.
Age: This variable countains the age of the counstomer.
Tenure: This is how long the coustomer has been with the bank.
Balance: This ia the available balance of coustomer account at the time of data collection.
products_number: This is the ammount of servises coustomer signed up for with the bank.
credit_card: This states wither a customer has a credit card or not.
active_member: This checks if the counstomer is still active customer of the bank .
estimated_salary: The estimated gross salary of each customer.
churn: Has coustomer left or not. It is used as the dependent variable for modelling. 
### 3. Objectives
With this data, i would be implementing the following in python programming language:
1. Read data into pandas dataframe format. 
2. Explore 5 number summary of data using method in pandas and funtions.
3. Visualise distributions using appropriate visualisation technique.
4. Report on findings and conclusion based on analysis. 


#### Importing liabraries

In [1]:
import pandas as pd # Pandas liabray from data manipulation and analysis
import numpy as np # Numpy liabrary helps to perform mathematical operations on features in a data
import statistics as stats # Statistis liabray helps to perform divers stataistical operations
import matplotlib.pyplot as plt # plt and sns are visualisation tools, used for visulising data.
import seaborn as sns

#### Reading csv file to dataframe format
To be able to manipulate data using python, we have to read the data in dataframe(df) format. 
To do this we would used 'read_csv' method in pandas and pass the name of the csv file into this operation as an argument in perentesis. 

In [2]:
churn = pd.read_csv('Bank Customer Churn Prediction.csv')

#### Displaying the head and tail of churn df
Head and tail means displaying the first and last five rows of df. 
To do the we would use the '.head()' and '.tail()' methods from pd. 

In [3]:
churn.head()

customer_id  credit_score country  gender  age  tenure    balance  \
0     15634602           619  France  Female   42       2       0.00   
1     15647311           608   Spain  Female   41       1   83807.86   
2     15619304           502  France  Female   42       8  159660.80   
3     15701354           699  France  Female   39       1       0.00   
4     15737888           850   Spain  Female   43       2  125510.82   

   products_number  credit_card  active_member  estimated_salary  churn  
0                1            1              1         101348.88      1  
1                1            0              1         112542.58      0  
2                3            1              0         113931.57      1  
3                2            0              0          93826.63      0  
4                1            1              1          79084.10      0

In [4]:
churn.tail()

customer_id  credit_score  country  gender  age  tenure    balance  \
9995     15606229           771   France    Male   39       5       0.00   
9996     15569892           516   France    Male   35      10   57369.61   
9997     15584532           709   France  Female   36       7       0.00   
9998     15682355           772  Germany    Male   42       3   75075.31   
9999     15628319           792   France  Female   28       4  130142.79   

      products_number  credit_card  active_member  estimated_salary  churn  
9995                2            1              0          96270.64      0  
9996                1            1              1         101699.77      0  
9997                1            0              1          42085.58      1  
9998                2            1              0          92888.52      1  
9999                1            1              0          38190.78      0

#### Data size and type
The size is the number of rows and column in df. And the type is the type of data contained in each variable. 
To do this we would be using the '.shape()' and '.info()' methods from pd laibray.

In [6]:
churn.shape

(10000, 12)

In [7]:
churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customer_id       10000 non-null  int64  
 1   credit_score      10000 non-null  int64  
 2   country           10000 non-null  object 
 3   gender            10000 non-null  object 
 4   age               10000 non-null  int64  
 5   tenure            10000 non-null  int64  
 6   balance           10000 non-null  float64
 7   products_number   10000 non-null  int64  
 8   credit_card       10000 non-null  int64  
 9   active_member     10000 non-null  int64  
 10  estimated_salary  10000 non-null  float64
 11  churn             10000 non-null  int64  
dtypes: float64(2), int64(8), object(2)
memory usage: 937.6+ KB


Output from size operation suggests that their are 12 columns and 10000 rows in chrn df. Furthermore, info operation output shows that there are 2 categorical variable, 10 numerical variables out of which 8 are integers and 2 are floats.


In [9]:
churn['active_member'].unique()

array([1, 0], dtype=int64)

In [10]:
churn['churn'].unique()

array([1, 0], dtype=int64)

In [11]:
churn['credit_card'].unique()

array([1, 0], dtype=int64)